
# html lang
# language: zh-CN

# main menu navigation
menu:
  首页: index.html
  文章: archives
  标签: tags
  分类: categories
  关于: about

social:
  GitHub: https://github.com/aliyoge
  Weibo: http://weibo.com/kongkongss
  Twitter: https://twitter.com/WenjunHuang
  Facebook: https://www.facebook.com/wenjun.huang.129

# Google analytics
google_analytics:
# Baidu tongji
baidu_analytics:
# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname:
# Uyan
uyan_id:
# jiaThis id
# if you want to change the style of jiaThis, please go to chage the following file:
# theme/random/layouts/includes/jiathis.swig
jiaThis_uid: 
jiathisConfig:
  data_track_clickback: true
  summary: ""
  showClose: true
  shortUrl: false
  hideMore: false



# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/random.css
- /css/vegas.min.css
- /css/highlight-railscasts.css
# - //cdn.bootcss.com/highlight.js/9.7.0/styles/atelier-cave-light.min.css
- /css/jquery.fancybox.css
- /css/iconfont/iconfont.css
- /css/jquery.fancybox-thumbs.css
- /css/plyr.css

# scripts loaded in the end of the body
scripts:
- /js/jquery-2.2.3.min.js
- /js/vegas.min.js
- /js/random.js
- /js/highlight.pack.js
# - //cdn.bootcss.com/highlight.js/9.7.0/highlight.min.js
- /js/jquery.mousewheel.pack.js
- /js/jquery.fancybox.pack.js
- /js/jquery.fancybox-thumbs.js
- /js/plyr.js

# ignore visitor statistics on special server, for example on you local computer or debugging server
isIgnoreSpecialHostVisitor: true
ignoreHostList:
  - localhost
  - 127.0.0.1

# if you want to turn off the background images, pleaase set this value as true
turnoffBackgroundImage: 
  # home page
  index: false
  # arcihve / categories / tags
  post_list: false
  # post and page
  post: true
# when you turn off backgrounds, you can set a background color.
backgroundColor: E5E5E5
 
backgroundImages:
 - http://7xqztm.com1.z0.glb.clouddn.com/1.jpg?imageView2/1/w/__width__/h/__height__
 - http://7xqztm.com1.z0.glb.clouddn.com/bgimg_1.jpg?imageView2/1/w/__width__/h/__height__
 - http://7xqztm.com1.z0.glb.clouddn.com/2.jpg?imageView2/1/w/__width__/h/__height__
 - http://7xqztm.com1.z0.glb.clouddn.com/1007.jpg?imageView2/1/w/__width__/h/__height__
 - http://7xqztm.com1.z0.glb.clouddn.com/2Q==.jpg?imageView2/1/w/__width__/h/__height__
 - http://7xqztm.com1.z0.glb.clouddn.com/631283.jpg?imageView2/1/w/__width__/h/__height__

vegasConfig:
  # more about config http://vegas.jaysalvat.com/documentation/settings/
  # animation: 'random'
  # transition: 'swirlRight'
  preload­Image: true
  transition:
    - slideLeft2
    - slideRight2
    # - zoomIn
    # - swirLeft
    # - swirRight
    # - flash
    - flash2
  timer: true
  delay: 5000
  shuffle: false
  count: 28

unsplashConfig:
  # more about config on https://unsplash.it/
  # blur: true
  gravity: 'north' # north, east, south, west, center
  # greyscale: true

avatar: http://7xqztm.com1.z0.glb.clouddn.com/FullSizeRender.jpg

# do not like fancybox, set this as false, this will turn it off
fancybox: true

# set the visibility of hide button in left bottom.
hideButtonVisibility: true